spring:
  application:
    name: entrycontrol
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/entrycontrol
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
projeto:
  security:
    jwt:
      secret: Vs+7sKclXPSOdZsXXiJ/CZN2DOUD7P1EySdHZKS5v9cMcW9D3r7tehXTGSQege+46+xnaMa/5GzWgph8yzn1GA==
      expiration: 3600000