spring:
  application:
    name: entrycontrol
  datasource:
    url: jdbc:h2:mem:testdb
    username: user
    password: 123
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
projeto:
  security:
    jwt:
      secret: Vs+7sKclXPSOdZsXXiJ/CZN2DOUD7P1EySdHZKS5v9cMcW9D3r7tehXTGSQege+46+xnaMa/5GzWgph8yzn1GA==
      expiration: 3600000